<?php

namespace FrontBundle\Repository;

/**
 * TypeRepasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepasRepository extends \Doctrine\ORM\EntityRepository
{
}
